server:
  port: 7777
  context-path: /demo

mybatis:
  typeAliasesPackage: com.zcxy.demo.model
  mapperLocations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/video?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    static-path-pattern: /** # Path pattern used for static resources.
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    excluded-view-names:
    template-resolver-order:



